# Generated by Django 3.2.2 on 2021-05-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('class_hist', models.JSONField()),
                ('scheduled', models.BooleanField(default=False)),
                ('attempts', models.IntegerField()),
                ('email', models.URLField()),
                ('class_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grading_app.classlist', to_field='class_code')),
                ('instructor_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grading_app.instructors')),
            ],
        ),
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_domain_url', models.URLField()),
                ('date', models.DateTimeField()),
                ('passed', models.BooleanField(default=False)),
                ('interviewer_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grading_app.instructors')),
                ('student_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grading_app.student', to_field='student_id')),
            ],
        ),
        migrations.CreateModel(
            name='WhiteboardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_whiteboard', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('whiteboard_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grading_app.whiteboard')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identified', models.IntegerField()),
                ('visual', models.IntegerField()),
                ('ident_optimal', models.IntegerField()),
                ('presented', models.IntegerField()),
                ('syntax', models.IntegerField()),
                ('idioms', models.IntegerField()),
                ('best_solve', models.IntegerField()),
                ('asked', models.IntegerField()),
                ('step_through', models.IntegerField()),
                ('big_o', models.IntegerField()),
                ('testing', models.IntegerField()),
                ('verbal', models.IntegerField()),
                ('terms', models.IntegerField()),
                ('time', models.IntegerField()),
                ('over', models.IntegerField()),
                ('under', models.IntegerField()),
                ('readable', models.IntegerField()),
                ('whiteboard_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grading_app.whiteboard')),
            ],
        ),
        migrations.AddField(
            model_name='classlist',
            name='instructor_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grading_app.instructors'),
        ),
        migrations.CreateModel(
            name='CategoryNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpretation', models.TextField(default='')),
                ('solved_technical', models.TextField(default='')),
                ('analyzed_solution', models.TextField(default='')),
                ('communication', models.TextField(default='')),
                ('general', models.TextField(default='')),
                ('whiteboard_key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='grading_app.whiteboard')),
            ],
        ),
    ]
